export const UserApiUrl='auth'
export const CartApiUrl='carts'
export const LearnApiUrl='sign'
export const TestApiUrl='test'
export const BookApiUrl='books'
export const OrderApiUrl='orders'
export const ResultApiUrl='result'
export const ChatApiUrl='chat'
export const TaskApiUrl='task'


export const HomePageUrl='/'
export const ReportPageUrl='/report'
export const AboutPageUrl='/about'
export const ContactPageUrl='/contact'
export const UserPageUrl='/users'
export const LearnPageUrl='/learn'
export const TestPageUrl='/test'
export const ResultPageUrl='/result'
export const HistoryPageUrl='/history'
export const ChatPageUrl='/chat'
export const TaskPageUrl='/task'